### ISSUE TITLE
Unable to install DDE 3.6.3 as Job Engine on Dexter

### ISSUE THREAD

**Issue by JamesNewton** [cfry/dde#58]
Pulling down the current release of DDE, version 3.6.3, and installing it as a new job engine fails during install. See the console output below, and attached log file. The issue this time appears to be
https://github.com/tessel/node-usb
which may be a require from serialport (because that was the prior item) or might be something else. 
It's trying to find a pre-built binary for the given version of node, arm processor, and linux, but those aren't available, so it tries to build from source, and fails while building libusb/os/linux_udev.o without finding a file called libudev.h

Console messages:
````
root@localhost:~/Documents/dde# npm install
npm WARN deprecated three-orbitcontrols@2.110.3: three-js exposes real modules now via three/examples/jsm/...
npm WARN deprecated for example to import Orbit, do
npm WARN deprecated import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls'
npm WARN deprecated
npm WARN deprecated three-gltf-loader@1.111.0: Starting with three.js r103, GLTFLoader is included in the three package itself and installing three-gltf-loader is no longer necessary. It can be imported from 'three/examples/jsm/loaders/GLTFLoader'

> @serialport/bindings@8.0.8 install /root/Documents/dde/node_modules/@serialport/bindings
> prebuild-install --tag-prefix @serialport/bindings@ || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=arm libc= platform=linux)
make: Entering directory '/root/Documents/dde/node_modules/@serialport/bindings/build'
  CXX(target) Release/obj.target/bindings/src/serialport.o
  CXX(target) Release/obj.target/bindings/src/serialport_unix.o
  CXX(target) Release/obj.target/bindings/src/poller.o
  CXX(target) Release/obj.target/bindings/src/serialport_linux.o
  SOLINK_MODULE(target) Release/obj.target/bindings.node
  COPY Release/bindings.node
make: Leaving directory '/root/Documents/dde/node_modules/@serialport/bindings/build'

> usb@1.6.3 install /root/Documents/dde/node_modules/usb
> prebuild-install --verbose || node-gyp rebuild

prebuild-install info begin Prebuild-install version 5.3.6
prebuild-install info looking for cached prebuild @ /root/.npm/_prebuilds/2b648a-usb-v1.6.3-node-v67-linux-arm.tar.gz
prebuild-install http request GET https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v67-linux-arm.tar.gz
prebuild-install http 404 https://github.com/tessel/node-usb/releases/download/v1.6.3/usb-v1.6.3-node-v67-linux-arm.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=11.6.0 runtime=node arch=arm libc= platform=linux)
make: Entering directory '/root/Documents/dde/node_modules/usb/build'
  CC(target) Release/obj.target/libusb/libusb/libusb/core.o
  CC(target) Release/obj.target/libusb/libusb/libusb/descriptor.o
  CC(target) Release/obj.target/libusb/libusb/libusb/hotplug.o
  CC(target) Release/obj.target/libusb/libusb/libusb/io.o
  CC(target) Release/obj.target/libusb/libusb/libusb/strerror.o
  CC(target) Release/obj.target/libusb/libusb/libusb/sync.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/poll_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/threads_posix.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_usbfs.o
  CC(target) Release/obj.target/libusb/libusb/libusb/os/linux_udev.o
../libusb/libusb/os/linux_udev.c:40:21: fatal error: libudev.h: No such file or directory
compilation terminated.
libusb.target.mk:138: recipe for target 'Release/obj.target/libusb/libusb/libusb/os/linux_udev.o' failed
make: *** [Release/obj.target/libusb/libusb/libusb/os/linux_udev.o] Error 1
make: Leaving directory '/root/Documents/dde/node_modules/usb/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:188:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
gyp ERR! System Linux 4.4.30-xillinux-2.0
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/Documents/dde/node_modules/usb
gyp ERR! node -v v11.6.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN three-text2d@0.6.0 requires a peer of @types/three@* but none is installed. You must install peer dependencies yourself.
npm WARN dexter_dev_env@3.6.4 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! usb@1.6.3 install: `prebuild-install --verbose || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the usb@1.6.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-11-03T23_41_34_149Z-debug.log
root@localhost:~/Documents/dde# node -v
v11.6.0
````

**Comment by JamesNewton** [comment]
Debug log

[2020-11-03T23_41_34_149Z-debug.log](https://github.com/cfry/dde/files/5484751/2020-11-03T23_41_34_149Z-debug.log)

**Comment by JamesNewton** [comment]
May be related to:
https://github.com/tessel/node-usb/issues/284#issuecomment-439094227
